# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            logout: ~
            form_login:
                login_path: login
                check_path: login_check

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /datos_personales, roles: ROLE_ALUMNO }
        - { path: /datos_empresa, roles: ROLE_EMPRESA }
        - { path: ^/miperfil, roles: [ROLE_ALUMNO, ROLE_EMPRESA] }
        - { path: ^/misofertas, roles: [ROLE_ALUMNO, ROLE_EMPRESA] }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
        # in_memory:
        #     memory:
        #         users:
        #             alumno:  { password: alumno, roles: 'ROLE_ALUMNO' }
        #             empresa:  { password: empresa, roles: 'ROLE_EMPRESA' }
        #             admin: { password: admin, roles: 'ROLE_ADMIN' }
        main:
            entity:
                class: SalesianosMainBundle:User

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Salesianos\MainBundle\Entity\User: plaintext