# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }

        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /datospersonales, roles: ROLE_ALUMNO }
        - { path: /datosempresa, roles: ROLE_EMPRESA }
        - { path: ^/miperfil, roles: [ROLE_ALUMNO, ROLE_EMPRESA] }
        - { path: ^/misofertas, roles: [ROLE_ALUMNO, ROLE_EMPRESA] }
        - { path: ^/nuevaoferta, roles: ROLE_EMPRESA }
        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512